### ISSUE TITLE
M1: TODO some stuff

### ISSUE THREAD

**Issue by neallithic64** [neallithic64/capstn-mmchd#64]
commits 29a7b09c8d88f7f65cc161730ecd3245a4b42622 and 26942b91c4c307be0be2d0985790d029a6d98353 have working functionalities, but these are not enough. todos below:

TODO:
- [x] segregating cases to CIF and CRF (data tables)
- [x] missing duplicate validation (patient and address; controller work)
- [x] need to prepare the return object from controller for the data tables
- [x] need to prepare JOIN statements for the data tables too

can't remember others, will add more to this later on

**Comment by neallithic64** [comment]
data tables are complete, just need to tweak what values are being sent to the frontend. will close this.
